version: '3.8'


services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '80:80'
    depends_on:
      - backend
     


  backend:
    build:
      context: ./backend
    ports:
      - '8080:8080'
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DATABASE_URL: jdbc:postgresql://database:5432/burgerbuilder
      DATABASE_USER: postgres
      DATABASE_PASSWORD: YourStrong!Passw0rd
    depends_on:
      - database


  database:
    image: postgres:15-alpine
    container_name: burgerbuilder-db
    environment:
      - POSTGRES_DB=burgerbuilder
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=YourStrong!Passw0rd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: