name: CI

on:
  pull_request:
  push:
    branches: ["*"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Backend tests
        working-directory: backend
        run: mvn -B -ntp -DskipTests=false -Dnet.bytebuddy.experimental=true test

      - name: Upload backend test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-reports
          path: |
            backend/target/surefire-reports/**/*.xml
            backend/target/failsafe-reports/**/*.xml
          if-no-files-found: ignore

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Frontend install & build
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image (amd64) — dry run
        run: |
          docker buildx build --platform linux/amd64 \
            -f backend/Dockerfile \
            -t ih-backend:ci \
            . --load

      - name: Build frontend image (amd64) — dry run
        run: |
          docker buildx build --platform linux/amd64 \
            -f frontend/Dockerfile \
            -t ih-frontend:ci \
            . --load
