# .github/workflows/deploy.yml
name: Build and Push to ACR

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Login to ACR
        run: az acr login --name ${{ secrets.ACR_NAME }}
      
      - name: Build and Push Backend
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/burger-backend:latest ./backend
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/burger-backend:latest
      
      - name: Build and Push Frontend
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/burger-frontend:latest ./frontend
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/burger-frontend:latest
